// 42 industries — mirrored from the Phaos AI Voice project (displayName field).
// Sorted alphabetically.
export const INDUSTRIES: string[] = [
  "Appliance Repair Services",
  "Automotive Repair Shops",
  "Boutique Hotels & Hospitality",
  "Catering & Event Services",
  "Chiropractors & Physical Therapy Clinics",
  "CPA & Accounting Firms",
  "Daycare & Childcare Centers",
  "Dental Practices",
  "Document Solutions",
  "E-commerce & Retail Support",
  "Electrical Services",
  "Funeral Homes",
  "General Business",
  "Gyms & Fitness Centers",
  "Hair Salons & Day Spas",
  "Healthcare & Medical Clinics",
  "Home Cleaning Services",
  "HVAC Services",
  "Insurance Agencies",
  "IT Support & Managed Service Providers (MSPs)",
  "Junk Removal & Hauling",
  "Landscaping & Lawn Care Services",
  "Law Firms & Legal Services",
  "Locksmiths & Emergency Services",
  "Moving & Storage Companies",
  "Pest Control Companies",
  "Pet Grooming, Boarding & Dog Daycares",
  "Photography & Videography Studios",
  "Plumbing Services",
  "Pool Cleaning & Maintenance Companies",
  "Printing Services",
  "Private Tutoring & Education Centers",
  "Property Management Companies",
  "Real Estate Agencies",
  "Roofing Contractors",
  "Self-Storage Facilities",
  "Signage & Display Companies",
  "Solar Energy Installers",
  "Staffing & Recruitment Agencies",
  "Travel & Tour Operators",
  "Veterinary Clinics",
  "Waste Management Companies",
];
