/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperadminIndexRouteImport } from './routes/superadmin.index'
import { Route as PhomoIndexRouteImport } from './routes/phomo/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PhomoResetPasswordRouteImport } from './routes/phomo/reset-password'
import { Route as PhomoAuthRouteImport } from './routes/phomo/auth'
import { Route as PhomoAdminRouteImport } from './routes/phomo/admin'
import { Route as OnboardingScheduleRouteImport } from './routes/onboarding.schedule'
import { Route as OnboardingManageRouteImport } from './routes/onboarding.manage'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CommitmentSuccessRouteImport } from './routes/commitment.success'
import { Route as AdminEditorRouteImport } from './routes/admin.editor'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicSetupAdminRouteImport } from './routes/api/public/setup-admin'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPhomoNotifyRouteImport } from './routes/api/public/phomo.notify'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments.webhook'
import { Route as ApiPublicCronMonthlyUsageRouteImport } from './routes/api/public/cron.monthly-usage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminIndexRoute = SuperadminIndexRouteImport.update({
  id: '/superadmin/',
  path: '/superadmin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhomoIndexRoute = PhomoIndexRouteImport.update({
  id: '/phomo/',
  path: '/phomo/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhomoResetPasswordRoute = PhomoResetPasswordRouteImport.update({
  id: '/phomo/reset-password',
  path: '/phomo/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PhomoAuthRoute = PhomoAuthRouteImport.update({
  id: '/phomo/auth',
  path: '/phomo/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PhomoAdminRoute = PhomoAdminRouteImport.update({
  id: '/phomo/admin',
  path: '/phomo/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingScheduleRoute = OnboardingScheduleRouteImport.update({
  id: '/onboarding/schedule',
  path: '/onboarding/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingManageRoute = OnboardingManageRouteImport.update({
  id: '/onboarding/manage',
  path: '/onboarding/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitmentSuccessRoute = CommitmentSuccessRouteImport.update({
  id: '/commitment/success',
  path: '/commitment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEditorRoute = AdminEditorRouteImport.update({
  id: '/admin/editor',
  path: '/admin/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSetupAdminRoute = ApiPublicSetupAdminRouteImport.update({
  id: '/api/public/setup-admin',
  path: '/api/public/setup-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPhomoNotifyRoute = ApiPublicPhomoNotifyRouteImport.update({
  id: '/api/public/phomo/notify',
  path: '/api/public/phomo/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronMonthlyUsageRoute =
  ApiPublicCronMonthlyUsageRouteImport.update({
    id: '/api/public/cron/monthly-usage',
    path: '/api/public/cron/monthly-usage',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/editor': typeof AdminEditorRoute
  '/commitment/success': typeof CommitmentSuccessRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/onboarding/manage': typeof OnboardingManageRoute
  '/onboarding/schedule': typeof OnboardingScheduleRoute
  '/phomo/admin': typeof PhomoAdminRoute
  '/phomo/auth': typeof PhomoAuthRoute
  '/phomo/reset-password': typeof PhomoResetPasswordRoute
  '/admin/': typeof AdminIndexRoute
  '/phomo/': typeof PhomoIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/api/public/setup-admin': typeof ApiPublicSetupAdminRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/cron/monthly-usage': typeof ApiPublicCronMonthlyUsageRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/phomo/notify': typeof ApiPublicPhomoNotifyRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/editor': typeof AdminEditorRoute
  '/commitment/success': typeof CommitmentSuccessRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/onboarding/manage': typeof OnboardingManageRoute
  '/onboarding/schedule': typeof OnboardingScheduleRoute
  '/phomo/admin': typeof PhomoAdminRoute
  '/phomo/auth': typeof PhomoAuthRoute
  '/phomo/reset-password': typeof PhomoResetPasswordRoute
  '/admin': typeof AdminIndexRoute
  '/phomo': typeof PhomoIndexRoute
  '/superadmin': typeof SuperadminIndexRoute
  '/api/public/setup-admin': typeof ApiPublicSetupAdminRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/cron/monthly-usage': typeof ApiPublicCronMonthlyUsageRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/phomo/notify': typeof ApiPublicPhomoNotifyRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/editor': typeof AdminEditorRoute
  '/commitment/success': typeof CommitmentSuccessRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/onboarding/manage': typeof OnboardingManageRoute
  '/onboarding/schedule': typeof OnboardingScheduleRoute
  '/phomo/admin': typeof PhomoAdminRoute
  '/phomo/auth': typeof PhomoAuthRoute
  '/phomo/reset-password': typeof PhomoResetPasswordRoute
  '/admin/': typeof AdminIndexRoute
  '/phomo/': typeof PhomoIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/api/public/setup-admin': typeof ApiPublicSetupAdminRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/cron/monthly-usage': typeof ApiPublicCronMonthlyUsageRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/phomo/notify': typeof ApiPublicPhomoNotifyRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/editor'
    | '/commitment/success'
    | '/email/unsubscribe'
    | '/onboarding/manage'
    | '/onboarding/schedule'
    | '/phomo/admin'
    | '/phomo/auth'
    | '/phomo/reset-password'
    | '/admin/'
    | '/phomo/'
    | '/superadmin/'
    | '/api/public/setup-admin'
    | '/lovable/email/suppression'
    | '/api/public/cron/monthly-usage'
    | '/api/public/payments/webhook'
    | '/api/public/phomo/notify'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/editor'
    | '/commitment/success'
    | '/email/unsubscribe'
    | '/onboarding/manage'
    | '/onboarding/schedule'
    | '/phomo/admin'
    | '/phomo/auth'
    | '/phomo/reset-password'
    | '/admin'
    | '/phomo'
    | '/superadmin'
    | '/api/public/setup-admin'
    | '/lovable/email/suppression'
    | '/api/public/cron/monthly-usage'
    | '/api/public/payments/webhook'
    | '/api/public/phomo/notify'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/admin/editor'
    | '/commitment/success'
    | '/email/unsubscribe'
    | '/onboarding/manage'
    | '/onboarding/schedule'
    | '/phomo/admin'
    | '/phomo/auth'
    | '/phomo/reset-password'
    | '/admin/'
    | '/phomo/'
    | '/superadmin/'
    | '/api/public/setup-admin'
    | '/lovable/email/suppression'
    | '/api/public/cron/monthly-usage'
    | '/api/public/payments/webhook'
    | '/api/public/phomo/notify'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminEditorRoute: typeof AdminEditorRoute
  CommitmentSuccessRoute: typeof CommitmentSuccessRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  OnboardingManageRoute: typeof OnboardingManageRoute
  OnboardingScheduleRoute: typeof OnboardingScheduleRoute
  PhomoAdminRoute: typeof PhomoAdminRoute
  PhomoAuthRoute: typeof PhomoAuthRoute
  PhomoResetPasswordRoute: typeof PhomoResetPasswordRoute
  AdminIndexRoute: typeof AdminIndexRoute
  PhomoIndexRoute: typeof PhomoIndexRoute
  SuperadminIndexRoute: typeof SuperadminIndexRoute
  ApiPublicSetupAdminRoute: typeof ApiPublicSetupAdminRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicCronMonthlyUsageRoute: typeof ApiPublicCronMonthlyUsageRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicPhomoNotifyRoute: typeof ApiPublicPhomoNotifyRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/': {
      id: '/superadmin/'
      path: '/superadmin'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof SuperadminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phomo/': {
      id: '/phomo/'
      path: '/phomo'
      fullPath: '/phomo/'
      preLoaderRoute: typeof PhomoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phomo/reset-password': {
      id: '/phomo/reset-password'
      path: '/phomo/reset-password'
      fullPath: '/phomo/reset-password'
      preLoaderRoute: typeof PhomoResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phomo/auth': {
      id: '/phomo/auth'
      path: '/phomo/auth'
      fullPath: '/phomo/auth'
      preLoaderRoute: typeof PhomoAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phomo/admin': {
      id: '/phomo/admin'
      path: '/phomo/admin'
      fullPath: '/phomo/admin'
      preLoaderRoute: typeof PhomoAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/schedule': {
      id: '/onboarding/schedule'
      path: '/onboarding/schedule'
      fullPath: '/onboarding/schedule'
      preLoaderRoute: typeof OnboardingScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/manage': {
      id: '/onboarding/manage'
      path: '/onboarding/manage'
      fullPath: '/onboarding/manage'
      preLoaderRoute: typeof OnboardingManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commitment/success': {
      id: '/commitment/success'
      path: '/commitment/success'
      fullPath: '/commitment/success'
      preLoaderRoute: typeof CommitmentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/editor': {
      id: '/admin/editor'
      path: '/admin/editor'
      fullPath: '/admin/editor'
      preLoaderRoute: typeof AdminEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/setup-admin': {
      id: '/api/public/setup-admin'
      path: '/api/public/setup-admin'
      fullPath: '/api/public/setup-admin'
      preLoaderRoute: typeof ApiPublicSetupAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/phomo/notify': {
      id: '/api/public/phomo/notify'
      path: '/api/public/phomo/notify'
      fullPath: '/api/public/phomo/notify'
      preLoaderRoute: typeof ApiPublicPhomoNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/monthly-usage': {
      id: '/api/public/cron/monthly-usage'
      path: '/api/public/cron/monthly-usage'
      fullPath: '/api/public/cron/monthly-usage'
      preLoaderRoute: typeof ApiPublicCronMonthlyUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminEditorRoute: AdminEditorRoute,
  CommitmentSuccessRoute: CommitmentSuccessRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  OnboardingManageRoute: OnboardingManageRoute,
  OnboardingScheduleRoute: OnboardingScheduleRoute,
  PhomoAdminRoute: PhomoAdminRoute,
  PhomoAuthRoute: PhomoAuthRoute,
  PhomoResetPasswordRoute: PhomoResetPasswordRoute,
  AdminIndexRoute: AdminIndexRoute,
  PhomoIndexRoute: PhomoIndexRoute,
  SuperadminIndexRoute: SuperadminIndexRoute,
  ApiPublicSetupAdminRoute: ApiPublicSetupAdminRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicCronMonthlyUsageRoute: ApiPublicCronMonthlyUsageRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicPhomoNotifyRoute: ApiPublicPhomoNotifyRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
